// Build-time i18n generator.
//
// Reads the English source of truth (src/i18n/en.js) and writes a generated
// translation file (src/i18n/<lang>.js) for each target language, using
// Google Translate's free (unofficial) endpoint — no API key required.
//
//   npm run i18n:translate            # regenerates Sinhala (si)
//   npm run i18n:translate -- --lang si,ta   # multiple languages
//
// This runs at BUILD time only. The app itself ships static translation files
// and never calls a translation API at runtime, so it stays fast and offline.
//
// Notes / safeguards:
//   - {{placeholders}} are preserved by translating only the text around them.
//   - Segments without letters (order IDs, numbers, dashes) are kept as-is.
//   - PRESERVE_KEYS are copied verbatim from English (brand, formats, etc.).
//   - Identical segments are cached so repeats stay consistent and cheap.
//   - On any failure for a key, it falls back to the English string + warns.

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const I18N_DIR = resolve(__dirname, '../src/i18n')

// Keys copied verbatim from English (never machine-translated).
const PRESERVE_KEYS = new Set([
  'brand.name', // brand name stays "Bakeriya" in every language
  'track.placeholder', // ORD-XXXXXXXX format hint
  'lang.english', // language names show in their own script
  'lang.sinhala'
])

const args = process.argv.slice(2)
function argValue(flag) {
  const i = args.indexOf(flag)
  return i !== -1 ? args[i + 1] : undefined
}
const LANGS = (argValue('--lang') || 'si').split(',').map((s) => s.trim()).filter(Boolean)

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const hasLetters = (s) => /[A-Za-z]/.test(s)

async function translateSegment(text, lang, cache) {
  const key = text
  if (cache.has(key)) return cache.get(key)

  const url =
    'https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=' +
    encodeURIComponent(lang) +
    '&dt=t&q=' +
    encodeURIComponent(text)

  let lastErr
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url)
      if (!res.ok) throw new Error('HTTP ' + res.status)
      const data = await res.json()
      const out = data[0].map((seg) => seg[0]).join('')
      cache.set(key, out)
      return out
    } catch (err) {
      lastErr = err
      await sleep(400 * (attempt + 1)) // back off, endpoint is rate-limited
    }
  }
  throw lastErr
}

// Translate one value, keeping {{placeholders}} and letter-free bits intact.
async function translateValue(value, lang, cache) {
  const parts = value.split(/(\{\{\w+\}\})/) // keep the placeholders as parts
  const out = []
  for (const part of parts) {
    if (part === '' || /^\{\{\w+\}\}$/.test(part) || !hasLetters(part)) {
      out.push(part)
      continue
    }
    // Preserve leading/trailing whitespace the translator would trim.
    const lead = part.match(/^\s*/)[0]
    const trail = part.match(/\s*$/)[0]
    const translated = await translateSegment(part.trim(), lang, cache)
    out.push(lead + translated + trail)
    await sleep(200)
  }
  return out.join('')
}

function serialize(lang, map) {
  const lines = Object.entries(map).map(
    ([k, v]) => '  ' + JSON.stringify(k) + ': ' + JSON.stringify(v) + ','
  )
  // drop trailing comma on the last entry for cleanliness
  if (lines.length) lines[lines.length - 1] = lines[lines.length - 1].replace(/,$/, '')
  return (
    `// AUTO-GENERATED by scripts/translate-i18n.mjs — do not edit by hand.\n` +
    `// Regenerate with: npm run i18n:translate${lang === 'si' ? '' : ` -- --lang ${lang}`}\n` +
    `// Source of truth: src/i18n/en.js\n` +
    `/* eslint-disable */\n` +
    `export const ${lang} = {\n${lines.join('\n')}\n}\n`
  )
}

async function main() {
  const { en } = await import(pathToFileURL(resolve(I18N_DIR, 'en.js')).href)
  const keys = Object.keys(en)
  console.log(`Source: ${keys.length} keys. Target languages: ${LANGS.join(', ')}\n`)

  for (const lang of LANGS) {
    const cache = new Map()
    const map = {}
    let failed = 0
    for (let i = 0; i < keys.length; i++) {
      const key = keys[i]
      if (PRESERVE_KEYS.has(key)) {
        map[key] = en[key]
        continue
      }
      try {
        map[key] = await translateValue(en[key], lang, cache)
      } catch (err) {
        map[key] = en[key] // safe fallback: English
        failed++
        console.warn(`  ! ${key}: ${err.message} — kept English`)
      }
      process.stdout.write(`\r[${lang}] ${i + 1}/${keys.length} keys…   `)
    }
    const file = resolve(I18N_DIR, `${lang}.js`)
    await writeFile(file, serialize(lang, map), 'utf8')
    console.log(`\r[${lang}] done — wrote src/i18n/${lang}.js (${keys.length} keys, ${failed} fell back to English)`)
  }
}

main().catch((err) => {
  console.error('\nTranslation failed:', err)
  process.exit(1)
})
